version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.22.1
    - 8.24.0
    - 8.27.0
    - 8.28.1
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.2
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: livewire/livewire
    versions:
    - 2.3.12
    - 2.3.14
    - 2.3.15
    - 2.3.17
    - 2.3.18
    - 2.3.8
    - 2.4.0
    - 2.4.1
    - 2.4.2
    - 2.4.3
  - dependency-name: laravel/sail
    versions:
    - 1.3.1
    - 1.4.1
    - 1.4.10
    - 1.4.11
    - 1.4.12
    - 1.4.4
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: nunomaduro/larastan
    versions:
    - 0.7.0
    - 0.7.1
    - 0.7.2
    - 0.7.3
  - dependency-name: facade/ignition
    versions:
    - 2.5.12
    - 2.5.13
    - 2.5.14
    - 2.6.0
    - 2.7.0
    - 2.8.2
  - dependency-name: phpseclib/phpseclib
    versions:
    - 3.0.7
  - dependency-name: spatie/laravel-ray
    versions:
    - 1.12.4
    - 1.12.6
    - 1.13.0
    - 1.14.0
    - 1.15.1
    - 1.17.1
    - 1.17.2
  - dependency-name: pestphp/pest
    versions:
    - 1.0.2
    - 1.0.3
    - 1.0.4
  - dependency-name: laravel/socialite
    versions:
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: spatie/laravel-permission
    versions:
    - 4.0.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
  - dependency-name: laravel/ui
    versions:
    - 3.2.0
  - dependency-name: barryvdh/laravel-ide-helper
    versions:
    - 2.9.0
  - dependency-name: fideloper/proxy
    versions:
    - 4.4.1
  - dependency-name: spatie/laravel-activitylog
    versions:
    - 3.16.1
  - dependency-name: fzaninotto/faker
    versions:
    - 1.9.2
  - dependency-name: lab404/laravel-impersonate
    versions:
    - 1.7.2
